name: Get Kengxxiao/ArknightsGameData latest commit SHA
on:
  schedule:
    # Every 15 minutes
    - cron: "0/15 * * * *"
jobs:
  get-commit-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch latest commit SHA
        run: |
          SHA=$(curl -sL https://api.github.com/repos/Kengxxiao/ArknightsGameData/commits/master | jq -r ".sha")
          if [ "$SHA" != "null" ]; then 
            echo $SHA > data/.game-data-sha
          fi
      - name: Check for modified files
        id: git-check
        run: echo "modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT
      - name: Commit & push latest commit SHA
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Mizuki'
          git config --global user.email 'mizuki@arknights'
          git commit -am "chore: update latest game data commit SHA" \
            -m "This is an automated commit triggered by GitHub Actions. Data repository: Kengxxiao/ArknightsGameData"
          git push
